import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { Case, Draft, EvidenceItem, TimelineEvent } from "@/db/schema";
import { EVIDENCE_TEMPLATES } from "@/lib/content/evidence-templates";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 12, fontWeight: "bold" },
  section: { marginTop: 16, marginBottom: 8 },
  heading: { fontSize: 13, fontWeight: "bold", marginBottom: 6 },
  line: { marginBottom: 4 },
  disclaimer: {
    marginTop: 24,
    fontSize: 9,
    color: "#666",
  },
});

type ExportInput = {
  case: Case;
  evidence: EvidenceItem[];
  timeline: TimelineEvent[];
  draft: Draft | null;
};

function EvidenceExportDoc({ data }: { data: ExportInput }) {
  const { case: c, evidence, timeline, draft } = data;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Proof & Path — Case Summary</Text>
        <Text style={styles.line}>{c.title}</Text>
        <Text style={styles.line}>Status: {c.status.replace(/_/g, " ")}</Text>

        <View style={styles.section}>
          <Text style={styles.heading}>Case facts</Text>
          {c.item ? <Text style={styles.line}>Item: {c.item}</Text> : null}
          {c.retailer ? (
            <Text style={styles.line}>Retailer: {c.retailer}</Text>
          ) : null}
          {c.whenApprox ? (
            <Text style={styles.line}>When: {c.whenApprox}</Text>
          ) : null}
          {c.desiredOutcome ? (
            <Text style={styles.line}>Desired outcome: {c.desiredOutcome}</Text>
          ) : null}
          {c.whatHappened ? (
            <Text style={styles.line}>What happened: {c.whatHappened}</Text>
          ) : null}
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Evidence index</Text>
          {evidence.map((item) => {
            const template = EVIDENCE_TEMPLATES.find(
              (t) => t.id === item.templateId,
            );
            return (
              <Text key={item.id} style={styles.line}>
                {template?.name ?? item.templateId} — {item.status}
              </Text>
            );
          })}
        </View>

        {draft ? (
          <View style={styles.section}>
            <Text style={styles.heading}>Draft correspondence</Text>
            <Text style={styles.line}>{draft.content}</Text>
          </View>
        ) : null}

        <View style={styles.section}>
          <Text style={styles.heading}>Timeline</Text>
          {timeline.map((event) => (
            <Text key={event.id} style={styles.line}>
              {new Date(event.occurredAt).toLocaleDateString("en-AU")} —{" "}
              {event.title}
            </Text>
          ))}
        </View>

        <Text style={styles.disclaimer}>
          Independent general information and organisation support — not legal
          advice and not a government service. Generated by Proof & Path.
        </Text>
      </Page>
    </Document>
  );
}

export async function buildCaseExportPdf(data: ExportInput) {
  const buffer = await renderToBuffer(<EvidenceExportDoc data={data} />);
  return Buffer.from(buffer).toString("base64");
}
